package com.weiweb.system.dao;

import java.util.List;
import java.util.Map;

import com.weiweb.system.model.SysDictDetail;

public interface SysDictDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	int deleteByPrimaryKey(String detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	int insert(SysDictDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	int insertSelective(SysDictDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	SysDictDetail selectByPrimaryKey(String detailId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	int updateByPrimaryKeySelective(SysDictDetail record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_dict_detail
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	int updateByPrimaryKey(SysDictDetail record);

	List<SysDictDetail> selectByDictType(String dictType);
	
	
}