package com.weiweb.system.dao;

import com.weiweb.system.model.SysDictDetail;

public interface SysDictDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    int deleteByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    int insert(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    int insertSelective(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    SysDictDetail selectByPrimaryKey(String detailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    int updateByPrimaryKeySelective(SysDictDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dict_detail
     *
     * @mbggenerated Thu Aug 24 10:36:07 CST 2017
     */
    int updateByPrimaryKey(SysDictDetail record);
}