package com.weiweb.admin.system.model;

public class SysDictDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.dict_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String dictType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_name
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_code
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_sort
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailSort;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_state
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_content
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailContent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.detail_remark
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String detailRemark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.create_time
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_dict_detail.create_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	private Integer createId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_id
	 * @return  the value of sys_dict_detail.detail_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailId() {
		return detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_id
	 * @param detailId  the value for sys_dict_detail.detail_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailId(String detailId) {
		this.detailId = detailId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.dict_type
	 * @return  the value of sys_dict_detail.dict_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDictType() {
		return dictType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.dict_type
	 * @param dictType  the value for sys_dict_detail.dict_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDictType(String dictType) {
		this.dictType = dictType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_name
	 * @return  the value of sys_dict_detail.detail_name
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailName() {
		return detailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_name
	 * @param detailName  the value for sys_dict_detail.detail_name
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailName(String detailName) {
		this.detailName = detailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_code
	 * @return  the value of sys_dict_detail.detail_code
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailCode() {
		return detailCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_code
	 * @param detailCode  the value for sys_dict_detail.detail_code
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailCode(String detailCode) {
		this.detailCode = detailCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_sort
	 * @return  the value of sys_dict_detail.detail_sort
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailSort() {
		return detailSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_sort
	 * @param detailSort  the value for sys_dict_detail.detail_sort
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailSort(String detailSort) {
		this.detailSort = detailSort;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_type
	 * @return  the value of sys_dict_detail.detail_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailType() {
		return detailType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_type
	 * @param detailType  the value for sys_dict_detail.detail_type
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailType(String detailType) {
		this.detailType = detailType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_state
	 * @return  the value of sys_dict_detail.detail_state
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailState() {
		return detailState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_state
	 * @param detailState  the value for sys_dict_detail.detail_state
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailState(String detailState) {
		this.detailState = detailState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_content
	 * @return  the value of sys_dict_detail.detail_content
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailContent() {
		return detailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_content
	 * @param detailContent  the value for sys_dict_detail.detail_content
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailContent(String detailContent) {
		this.detailContent = detailContent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.detail_remark
	 * @return  the value of sys_dict_detail.detail_remark
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getDetailRemark() {
		return detailRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.detail_remark
	 * @param detailRemark  the value for sys_dict_detail.detail_remark
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setDetailRemark(String detailRemark) {
		this.detailRemark = detailRemark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.create_time
	 * @return  the value of sys_dict_detail.create_time
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.create_time
	 * @param createTime  the value for sys_dict_detail.create_time
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_dict_detail.create_id
	 * @return  the value of sys_dict_detail.create_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public Integer getCreateId() {
		return createId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_dict_detail.create_id
	 * @param createId  the value for sys_dict_detail.create_id
	 * @mbggenerated  Thu Aug 24 11:05:18 CST 2017
	 */
	public void setCreateId(Integer createId) {
		this.createId = createId;
	}
}