package com.weiweb.system.model;

import java.util.Date;

public class SysConfig {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.create_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.modify_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private Date modifyDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.param_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private String paramName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.param_type
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private String paramType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.param_value
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private String paramValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.show_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    private String showName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.create_date
     *
     * @return the value of sys_config.create_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.create_date
     *
     * @param createDate the value for sys_config.create_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.modify_date
     *
     * @return the value of sys_config.modify_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.modify_date
     *
     * @param modifyDate the value for sys_config.modify_date
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.param_name
     *
     * @return the value of sys_config.param_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public String getParamName() {
        return paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.param_name
     *
     * @param paramName the value for sys_config.param_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setParamName(String paramName) {
        this.paramName = paramName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.param_type
     *
     * @return the value of sys_config.param_type
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public String getParamType() {
        return paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.param_type
     *
     * @param paramType the value for sys_config.param_type
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setParamType(String paramType) {
        this.paramType = paramType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.param_value
     *
     * @return the value of sys_config.param_value
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public String getParamValue() {
        return paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.param_value
     *
     * @param paramValue the value for sys_config.param_value
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setParamValue(String paramValue) {
        this.paramValue = paramValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.show_name
     *
     * @return the value of sys_config.show_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.show_name
     *
     * @param showName the value for sys_config.show_name
     *
     * @mbggenerated Fri Aug 25 14:05:11 CST 2017
     */
    public void setShowName(String showName) {
        this.showName = showName;
    }
}